### ISSUE TITLE
Can't use zsh in terminal

### ISSUE THREAD

**Issue by dmaes** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#23] opened 2019-06-16 10:52 UTC
I can use `/bin/sh` and `/bin/bash` in the built-in terminal, but not `/usr/bin/zsh` (or `/bin/zsh`).
A **'No such file or directory'** is returned.

**Comment by BjoernDaase** [comment] 2020-06-26 05:46
Unfortunately https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/24 did not help, the problem persists :(

**Comment by fpizzicol** [comment] 2020-06-30 20:30
Same issue, I'm using Manjaro 20.0.3, Kernel 5.7.
Command `$ which zsh` returns
`which: no zsh in (/app/bin:/usr/bin:)`

**Comment by tomwojcik** [comment] 2020-12-25 22:37
Same issue, but only when opening terminal from PyCharm.

**Comment by tomwojcik** [comment] 2020-12-25 23:25
I don't know how you installed your jetbrains apps but I think I know the source of the problem.

I just run into the same issue. I installed PyCharm from from linux store which is using flatpak to distribute apps. AFAIK it'd be dangerous to allow flatpak apps to access some os specific stuff such as symlinks or full $PATH. It happens that `/usr/zsh` is a symlink.

I removed the app and downloaded PyCharm from JetBrains website, like I always do. It immediately picked up zsh.

So, the source of the issue is flatpak itself and I don't think it can be resolved. If anything, it'd be nice to mention it in the docs.

https://www.jetbrains.com/help/pycharm/terminal-emulator.html#configure-the-terminal-emulator

**Comment by DanielNoga** [comment] 2022-07-30 23:11
> Just to comment on this if someone stumbles on this same issue. Solution is to change Shell Path under Settings > Tools > Terminal to: `flatpak-spawn --host zsh`
> 
> Note: if you are using zsh framework like zimfw and have jumping cursor problem just add TERM env variable: `flatpak-spawn --host --env=TERM=xterm-256color zsh`.

Thanks, it fixed my issue with using Docker plugin and trying to run docker-compose with error `Cannot run program "docker-compose"` too

**Comment by DennisPing** [comment] 2022-10-07 03:09
Commenting for future viewers. @tomwojcik is correct. The bug free way to install Intellij on Linux is through the [Jetbrains instructions](https://www.jetbrains.com/help/idea/installation-guide.html#1d570694). If you install it from a flatpak (Ubuntu store, flathub, etc), you run into all sorts of issues.

My zsh works out of the box now.

**Comment by aberry12085** [comment] 2022-12-30 02:09
Also could not run zsh when PhpStorm installed via Flatpak on PopOS. 

Re-installed with the JetBrains Toolbox and now it works fine.

That'll teach me.

**Comment by cesarhmatias** [comment] 2023-06-09 14:15
> --env=TERM=xterm-256color zsh

Thanks for your answer! I ran into this problem and it worked for me. 
My zsh is now correctly working with Flatpak's Pycharm.

**Comment by cesarhmatias** [comment] 2023-06-09 14:16
> Just to comment on this if someone stumbles on this same issue. Solution is to change Shell Path under Settings > Tools > Terminal to: `flatpak-spawn --host zsh`
> 
> Note: if you are using zsh framework like zimfw and have jumping cursor problem just add TERM env variable: `flatpak-spawn --host --env=TERM=xterm-256color zsh`.


Thanks for your answer! I ran into this problem and it worked for me. 
My zsh is now correctly working with Flatpak's Pycharm.

**Comment by carlocagnetta** [comment] 2024-05-25 16:51
This issue is persisting.
I got rid of snap and all its application because it was too heavy, to then stumble upon this problem.
This solution worked for me as well

> Just to comment on this if someone stumbles on this same issue. Solution is to change Shell Path under Settings > Tools > Terminal to: `flatpak-spawn --host zsh`
> 
> Note: if you are using zsh framework like zimfw and have jumping cursor problem just add TERM env variable: `flatpak-spawn --host --env=TERM=xterm-256color zsh`.

**Comment by spynom** [comment] 2024-09-05 21:17
> Just to comment on this if someone stumbles on this same issue. Solution is to change Shell Path under Settings > Tools > Terminal to: `flatpak-spawn --host zsh`
> 
> Note: if you are using zsh framework like zimfw and have jumping cursor problem just add TERM env variable: `flatpak-spawn --host --env=TERM=xterm-256color zsh`.

for those who are wondering "does it still work?", then yes it did work for me.

**Comment by xanscale** [comment] 2024-11-21 22:06
flatpak package is thinked to works in isolated env, in flatpak platform
this things is not a bug and the proposed workaround works

i will close this issue

**Closed by xanscale** 2024-11-21 22:06 UTC
